### ISSUE TITLE
Ability to use it with logrotate

### ISSUE THREAD

**Issue by codercms** [mnabialek/laravel-sql-logger#10]
Hello! It would be a greateful if you will add option to the config file that allow to write logs into single file.
https://linux.die.net/man/8/logrotate

**Comment by mnabialek** [comment]
Do you mean creating file in any format you want? For example you can set it to `sql.log` or `sql-%Y-%m-%d.log`? I considered something like this already. I hope I will be able to add this soon

**Comment by codercms** [comment]
Yes, it's exactly what i mean. Thanks :)

**Comment by mnabialek** [comment]
@codercms You can now set custom format of log files in 2.0 release by setting custom value for `SQL_LOGGER_ALL_QUERIES_FILE_NAME` and `SQL_LOGGER_SLOW_QUERIES_FILE_NAME` env variables
