### ISSUE TITLE
When a query has a character "?" the script throws an unhandled "QueryExecuted could not be converted to string" error

### ISSUE THREAD

**Issue by ramsesmoreno** [mnabialek/laravel-sql-logger#11]
If for some reason the line 109 of SqlLogger.php there is an error, it gets catch, but inside the catch, in like 111, $query seems unable to be converted to string:

"QueryExecuted could not be converted to string" error

**Comment by mnabialek** [comment]
Can you please give me example of such query? Also please make sure you are using latest 2.x version

**Comment by mnabialek** [comment]
I'm closing this now due to not enough information
