### ISSUE TITLE
bind params value problem

### ISSUE THREAD

**Issue by mits87** [mnabialek/laravel-sql-logger#12]
Hi,

I have piece of code:
``` php
$data = Map::select('map.*', DB::raw('AsText(position) as position'))
    ->whereRaw('Contains(ST_MakeEnvelope(ST_GeomFromText("POINT(? ?)"), ST_GeomFromText("POINT(? ?)")), position)', [
        $request->input('ne.lat'), $request->input('ne.lng'),
        $request->input('sw.lat'), $request->input('sw.lng')
    ])
    ->get();
```

and your script generate:

``` sql
select `maps`.*, AsText(position) as position from `maps` where Contains(ST_MakeEnvelope(ST_GeomFromText("POINT(? ?)"), ST_GeomFromText("POINT(? ?)")), position);
```

and the question is: how can I see full SQL with value (not with "?" mark)?

**Comment by mnabialek** [comment]
Unfortunately I believe this is not possible at the moment. All bindings inside quotes are considered as strings because we can have query like this:

```
SELECT * FROM users WHERE name = 'abc ?'
```

and it's hard to say here if we would like to use here parameter or maybe we should search for user that has really name **abc ?**
