### ISSUE TITLE
Lumen 5.6  Type error: Argument 1 passed to Mnabialek\LaravelVersion\Version::__construct() must implement interface Illuminate\Contracts\Foundation\Application, instance of Laravel\Lumen\Application given

### ISSUE THREAD

**Issue by imlewc** [mnabialek/laravel-sql-logger#13]
as title

**Comment by mnabialek** [comment]
Thanks for adding this issue. I will verify it and fix in few next days

**Comment by mnabialek** [comment]
@imlewc It should be fixed now. Make sure you update to latest release (2.0.2). Please confirm it's fine now. I've verified it in Lumen and it seems to be fine now.

**Comment by mnabialek** [comment]
I'm closing it due to inactivity. If it didn't solve the problem, please create new issue
