### ISSUE TITLE
Questions: How and where can I add more information

### ISSUE THREAD

**Issue by ocarlosapenas** [mnabialek/laravel-sql-logger#15]
Great library has helped me a lot to debug my apps.

I would like to know where I can change the registry that is made to add some more information that I would like to appear in the log.

**Comment by mnabialek** [comment]
Do you have any idea what would you like to add to log? I could consider adding it to package.

**Comment by ocarlosapenas** [comment]
If a User is logged, print in the LOG the USER_ID or/and Email

**Comment by mnabialek** [comment]
Unfortunately I didn't find the way to add this information (I'm getting quite strange error). If I find the way, I will add this into package.

**Comment by ocarlosapenas** [comment]
I also got errors when adding Auth, always get error 500

Em dom, 9 de set de 2018 às 09:01, Marcin Nabiałek <notifications@github.com>
escreveu:

**Comment by mnabialek** [comment]
I was playing with this a bit, but I think there is no reasonable way to do it at this moment or a lot of code has to be rewritten to make it possible. I'm closing this for now.
