### ISSUE TITLE
No support nesbot/carbon 2.x

### ISSUE THREAD

**Issue by andrey-helldar** [mnabialek/laravel-sql-logger#17]
Laravel 5.8 supports `nesbot/carbon` version `2.x`.
Will it support this package?

Maybe you should specify `"nesbot/carbon": "~1.0 | ~2.0"` in `composer.json`?

**Comment by mnabialek** [comment]
Thanks for report. Latest release (v2.2.1) now supports both Carbon 1 and 2

**Comment by andrey-helldar** [comment]
Thanks 👍
