### ISSUE TITLE
Constructor error

### ISSUE THREAD

**Issue by xixigou** [mnabialek/laravel-sql-logger#23]
Argument 3 passed to Mnabialek\LaravelSqlLogger\Objects\SqlQuery::__construct() must be of the type array, null given, called in /mnt/f/projects/phiaee.com/phiaee_platform/vendor/mnabialek/laravel-sql-logger/src/Query.php on line 42 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 3 passed to Mnabialek\\LaravelSqlLogger\\Objects\\SqlQuery::__construct() must be of the type array, null given, called in /mnt/f/projects/phiaee.com/phiaee_platform/vendor/mnabialek/laravel-sql-logger/src/Query.php on line 42 at /mnt/f/projects/phiaee.com/phiaee_platform/vendor/mnabialek/laravel-sql-logger/src/Objects/SqlQuery.php:39)

laravel/framework is v5.7.28 and laravel-sql-logger is v2.2.7.

[stacktrace]
#0 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/mnabialek/laravel-sql-logger/src/Query.php(42): Mnabialek\\LaravelSqlLogger\\Objects\\SqlQuery->__construct(1, Object(Illuminate\\Database\\Events\\QueryExecuted), NULL, NULL)
#1 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/mnabialek/laravel-sql-logger/src/SqlLogger.php(58): Mnabialek\\LaravelSqlLogger\\Query->get(1, Object(Illuminate\\Database\\Events\\QueryExecuted), NULL, NULL)
#2 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/mnabialek/laravel-sql-logger/src/Providers/ServiceProvider.php(94): Mnabialek\\LaravelSqlLogger\\SqlLogger->log(Object(Illuminate\\Database\\Events\\QueryExecuted), NULL, NULL)
#3 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(360): Mnabialek\\LaravelSqlLogger\\Providers\\ServiceProvider->Mnabialek\\LaravelSqlLogger\\Providers\\{closure}(Object(Illuminate\\Database\\Events\\QueryExecuted))
#4 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(209): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Illuminate\\\\Data...', Array)
#5 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Database/Connection.php(828): Illuminate\\Events\\Dispatcher->dispatch('Illuminate\\\\Data...')
#6 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Database/Connection.php(682): Illuminate\\Database\\Connection->event(Object(Illuminate\\Database\\Events\\QueryExecuted))
#7 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Database/Connection.php(635): Illuminate\\Database\\Connection->logQuery('select * from `...', Array, 447.52)
#8 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select * from `...', Array, Object(Closure))
#9 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2095): Illuminate\\Database\\Connection->select('select * from `...', Array, true)
#10 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2083): Illuminate\\Database\\Query\\Builder->runSelect()
#11 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2569): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#12 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2084): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#13 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(519): Illuminate\\Database\\Query\\Builder->get(Array)
#14 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(503): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#15 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(77): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#16 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php(52): Illuminate\\Database\\Eloquent\\Builder->first()
#17 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/tymon/jwt-auth/src/JWTGuard.php(82): Illuminate\\Auth\\EloquentUserProvider->retrieveById(2)
#18 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Auth/GuardHelpers.php(60): Tymon\\JWTAuth\\JWTGuard->user()
#19 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Auth/GuardHelpers.php(70): Tymon\\JWTAuth\\JWTGuard->check()
#20 /mnt/f/projects/phiaee.com/phiaee_platform/app/Http/Middleware/JwtAuthAdmin.php(38): Tymon\\JWTAuth\\JWTGuard->guest()
#21 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\JwtAuthAdmin->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#25 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#26 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#27 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#28 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#29 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#30 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/medz/cors/src/Laravel/Middleware/Cors.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Medz\\Cors\\Laravel\\Middleware\\Cors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#50 /mnt/f/projects/phiaee.com/phiaee_platform/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#51 /mnt/f/projects/phiaee.com/phiaee_platform/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#52 {main}
"}

**Comment by mnabialek** [comment]
Can you please code with query you are trying to run?

**Comment by xixigou** [comment]
1. run composer require mnabialek/laravel-sql-logger.

2. run php artisan vendor:publish and choose Mnabialek\LaravelSqlLogger\Providers\ServiceProvider.

3. config/sql_logger.php is default.

4. next, I write APIs with sql query. with that, Something went wrong.

**Comment by mnabialek** [comment]
Hi

Sorry for long time of waiting. I was not able to reproduce the issue. However I just released  v2.2.8 that should fix this. 

Please check and let me know if issue is fixed.
