### ISSUE TITLE
Bind Context Request_id to sql log 

### ISSUE THREAD

**Issue by Oranzh** [mnabialek/laravel-sql-logger#29]
I have made this middleware to my project, so laravel's log has one unique request id, but I hope the sql file have the same one request_id, so I think I will check one  client request is easier! 
How do I can to this ? Thanks for ur time!

`class AssignRequestId
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $requestId = (string) Str::uuid();

        Log::withContext([
            'request-id' => $requestId
        ]);

        return $next($request)->header('Request-Id', $requestId);
    }
}`

Now only the laravel log has request_id.
![image](https://user-images.githubusercontent.com/21193565/134462621-565a5a61-c137-41a1-bf4e-090bb1d88feb.png)

**Comment by mnabialek** [comment]
Hi @Oranzh Unfortunately this package doesn't support using Log. In addition `withContext` method was introduced in Laravel 8 so it I have to delay handling it. Also remember that using this package in production is not really recommended. This package is intended for local/dev usage to track number of queries.
