### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by 89gsc** [mnabialek/laravel-sql-logger#4]
Gave log directory 777 permissions and owner / group is correct but I only get errors about being unable to create the file. 

Is there anyway to set the file name to something like sql.log so I can manually make the file so this isn't happening.

**Comment by mnabialek** [comment]
At the moment it's not possible, maybe in future versions will be. However it seems to be a problem with your server permissions. Probably your www user is not the same as user you are logged in console and that's why you are getting those errors.

**Comment by klaravel** [comment]
When "sql" directory in log folder is not there it's generating error.

Either if we create manually or I have clone this package and added below code in beginning of function and working great.

File: https://github.com/mnabialek/laravel-sql-logger/blob/master/src/SqlLogger.php
Function: saveLog

``` php
if (!file_exists($this->directory)) {
   mkdir($this->directory, 0777, true);
}
```

**Comment by mnabialek** [comment]
This is expected behaviour. You need to create directory manually. We don't want to check if directory exists each time because of performance
