### ISSUE TITLE
No permission to write to log

### ISSUE THREAD

**Issue by smurfyuen** [mnabialek/laravel-sql-logger#7]
Hi ,
Once the file is created ,  the file does not have permission to write to the new file.
No write attribute on the file.
Cheers,
MIchael

**Comment by mnabialek** [comment]
You should make sure you configured your directory permissions in right way

**Comment by smurfyuen** [comment]
I think is the group problem. Thx

2017年9月9日 上午2:04 於 "Marcin Nabiałek" <notifications@github.com> 寫道：

**Comment by mnabialek** [comment]
Maybe yes, but script doesn't know your group. Make sure you use same user for http and console and make sure you set valid permissions on your local machine.
