### ISSUE TITLE
Is it possible to add a filter for excluding select statements?

### ISSUE THREAD

**Issue by simonschaufi** [mnabialek/laravel-sql-logger#9]
I'm only interested in update and delete statements. Could you add a possibility to filter out select (or any other type) statements?

**Comment by mnabialek** [comment]
Thanks for feature request. I will consider it soon

**Comment by mnabialek** [comment]
@simonschaufi This functionality has been added into new 2.0 release. By default all queries are logged but you can adjust `SQL_LOGGER_ALL_QUERIES_PATTERN` and `SQL_LOGGER_SLOW_QUERIES_PATTERN` env variables to match any regex you want

**Comment by simonschaufi** [comment]
thank you!
